<!-- Footer -->
<footer id="footer" data-cmsadmin-layout-footer="true">
	
	<!-- Social Navigation -->
	<div id="social-nav">
		<$social cssClass="socialMedia" /$>
	</div>
	<!-- /Social Navigation -->
	
	<!-- Footer Navigation -->
	<div id="footer-nav">
		<$rootmenu showHome="true"/$> 
	</div>
	<!-- /Footer Navigation -->
	
	<!-- Copyright -->
	<p id="copyright">    
		Copyright &copy; <$websitename/$>, <$date format="yyyy"/$>. All Rights Reserved.
	</p>
	<!-- /Copyright -->

</footer>
<!-- /Footer -->