<!-- Header -->
<header id="header" data-cmsadmin-layout-header="true">
	
	<!-- Branding -->
	<div id="branding" data-cmsadmin-layout-branding="true">
		<$logo href="/" maxwidth="600" maxheight="200" alt=""$>
		<div id="website-name">
			<a href="/"><$websitename/$></a>
		</div>
		<$/logo$>
	</div>
	<!-- /Branding -->
	
	<!-- Phone -->
	<div id="phone">
		Call Today: <a href="tel:555-555-5555" title="Call: 555-555-5555">555-555-5555</a>
	</div>
	<!-- /Phone -->
	
	<!-- Navigation -->
	<nav id="navigation" data-cmsadmin-layout-nav="true">
		<span class="nav-toggle icon-bars"></span>
		<span class="nav-toggle nav-close">x</span>
		<$globalmenu showLevels="1,2,3" alwaysShowChildren="true" showHome="true"/$>
	</nav>
	<!-- /Navigation -->

</header>
<!-- /Header -->