<head>

	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />   
	<meta content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" name="viewport" />

	<title><$pagetitle/$> | <$websitename/$></title>
	
	<!-- Fonts -->
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Merriweather:400,700|Raleway:200,300,400,500,700" />
	<link rel="stylesheet" type="text/css" href="fonts/icons.css" />
	<!-- /Fonts -->
	
	<!-- Styles -->
	<link rel="stylesheet" type="text/css" href="css/style.css"/>
	<!-- /Styles -->

	<!-- Scripts -->
	<!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
	<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<script type="text/javascript" src="js/script.js"></script>
	<!-- /Scripts -->

</head>